### ISSUE TITLE
Error when fetch user data

### ISSUE THREAD

**Issue by 3383389** [Snap-Kit/bitmoji-sample#13]
I trying to fetch user data in onLoginSucceeded method. But I get an error
`
    java.lang.NullPointerException: Attempt to invoke virtual method 'int retrofit.client.Response.getStatus()' on a null object reference
        at com.snapchat.kit.sdk.login.networking.a$1.failure(SourceFile:58)
        at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7036)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
`
query - "{me{bitmoji{avatar},displayName}}"

import gradle
implementation([
            'com.snapchat.kit.sdk:login:1.1.2',
            'com.snapchat.kit.sdk:core:1.1.2'
    ])

<string-array name="snap_connect_scopes">
        <item>https://auth.snapchat.com/oauth2/api/user.bitmoji.avatar</item>
        <item>https://auth.snapchat.com/oauth2/api/user.display_name</item>
    </string-array>

Maybe anyone can help with this issue?

**Comment by devanshp915** [comment]
Hey, how did you solve this?
