### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by 3383389** [Snap-Kit/bitmoji-sample#14]
Hi, in version 1.1.4 and 1.1.3 I have an issue
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
```
It happens after authorization in browser or native app
Where I should search solution?

**Comment by KhokharRavi** [comment]
I am facing similar issue.

**Comment by Volynskyi** [comment]
same

**Comment by Volynskyi** [comment]
> Hi, in version 1.1.4 and 1.1.3 I have an issue
> 
> ```
> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
>         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
> ```
> 
> It happens after authorization in browser or native app
> Where I should search solution?

Update to higher version. It helped me.

**Comment by klmnden** [comment]
Op

________________________________
Gönderen: Volodymyr Zhdan <notifications@github.com>
Gönderildi: Wednesday, August 7, 2019 10:16:26 PM
Kime: Snap-Kit/bitmoji-sample <bitmoji-sample@noreply.github.com>
Bilgi: Subscribed <subscribed@noreply.github.com>
Konu: Re: [Snap-Kit/bitmoji-sample] Error on login (#14)


same

**Comment by sudcha90** [comment]
Same issue. I updated to Android SDK 27 and above (which is very high!), but still getting the same error and the app crashes. Any inputs on how to resolve this issue?

Some search on error suggests that instead of getting JSON object, the program is getting a String in "mLoginStateChangedListener =
                    new LoginStateController.OnLoginStateChangedListener()".

Does anyone know how to fix this issue? thanks,

**Comment by MasaYanagida** [comment]
Me facing the same issue...😢

**Comment by Deloww** [comment]
[](https://github.com/Snap-Kit/bitmoji-sample/issues/29)
